export const errorCodes = {
    CODE: 401,
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_USER: 'INVALID_USER',
    INVALID_SESSION: 'INVALID_SESSION',
    USER_VALIDATION_FAILED: 'USER_VALIDATION_FAILED',
    INVALID_LOGGED_IN_USER: 'INVALID_LOGGED_IN_USER',
    EMPTY_USER_TOKEN: 'EMPTY_USER_TOKEN',
    INVALID_USER_TOKEN: 'INVALID_USER_TOKEN',
    INITIAL_LOGGED_IN_USER: 'INITIAL_LOGGED_IN_USER'
};

export const requestTypes = {
    FORGOT_PASSWORD_AUTH: 'FORGOT_PASSWORD',
    STANDARD_AUTH: 'STANDARD'
};
